// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQdysMQM3sbKC7FdrfRKfQ01Hiry_lLQ4',
    appId: '1:717376758532:web:d1511ccd09698197902651',
    messagingSenderId: '717376758532',
    projectId: 'machinerent-906a8',
    authDomain: 'machinerent-906a8.firebaseapp.com',
    databaseURL: 'https://machinerent-906a8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'machinerent-906a8.appspot.com',
    measurementId: 'G-RRL7NGTYKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtwFBcqc-Lx8xSMo-jWfQry2Mx66FCXek',
    appId: '1:717376758532:android:66212a35452511ed902651',
    messagingSenderId: '717376758532',
    projectId: 'machinerent-906a8',
    databaseURL: 'https://machinerent-906a8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'machinerent-906a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3sFZYhiCoP1asaNAY6Lr6e0dH2kS3nPk',
    appId: '1:717376758532:ios:1ca79ec882833cc3902651',
    messagingSenderId: '717376758532',
    projectId: 'machinerent-906a8',
    databaseURL: 'https://machinerent-906a8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'machinerent-906a8.appspot.com',
    iosBundleId: 'com.example.machinerent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3sFZYhiCoP1asaNAY6Lr6e0dH2kS3nPk',
    appId: '1:717376758532:ios:1ca79ec882833cc3902651',
    messagingSenderId: '717376758532',
    projectId: 'machinerent-906a8',
    databaseURL: 'https://machinerent-906a8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'machinerent-906a8.appspot.com',
    iosBundleId: 'com.example.machinerent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQdysMQM3sbKC7FdrfRKfQ01Hiry_lLQ4',
    appId: '1:717376758532:web:6e25ab3f6dd28ae7902651',
    messagingSenderId: '717376758532',
    projectId: 'machinerent-906a8',
    authDomain: 'machinerent-906a8.firebaseapp.com',
    databaseURL: 'https://machinerent-906a8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'machinerent-906a8.appspot.com',
    measurementId: 'G-443R5G24JK',
  );
}
